---
abstract: 'search for auctions at European eBay sites'
author:
  - "Martin 'Kingpin' Thurn, C<mthurn at cpan.org>, L<http://tinyurl.com/nn67z>."
build_requires:
  Bit::Vector: 0
  Date::Manip: 0
  ExtUtils::MakeMaker: 6.36
  IO::Capture::Stderr: 0
  Test::More: 0
  WWW::Search::Test: 2.284
configure_requires:
  ExtUtils::MakeMaker: 6.36
distribution_type: module
dynamic_config: 1
generated_by: 'Module::Install version 1.06'
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
module_name: WWW::Search::Ebay::Europe
name: WWW-Search-Ebay-Europe
no_index:
  directory:
    - inc
    - t
recommends:
  Test::Pod: 0
  Test::Pod::Coverage: 0
requires:
  Date::Manip: 0
  HTML::TreeBuilder: 0
  LWP::Simple: 0
  WWW::Search: 2.557
  WWW::Search::Ebay: 2.258
  WWW::SearchResult: 2.067
  perl: 5.005
resources:
  license: http://dev.perl.org/licenses/
version: 2.014
