---
author:
  - 'Martin Thurn <mthurn@cpan.org>'
build_requires:
  Bit::Vector: 0
  Date::Manip: 0
  IO::Capture::Stderr: 0
  Test::More: 0
  Test::Pod: 0
  Test::Pod::Coverage: 0
  WWW::Search::Test: 2.265
distribution_type: module
generated_by: 'Module::Install version 0.76'
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: WWW-Search-Ebay-Europe
no_index:
  directory:
    - inc
    - t
requires:
  Date::Manip: 0
  HTML::TreeBuilder: 0
  LWP::Simple: 0
  WWW::Search: 2.557
  WWW::Search::Ebay: 0
  WWW::SearchResult: 2.067
  perl: 5.005
resources:
  license: http://dev.perl.org/licenses/
version: 2.001
